### ISSUE TITLE
[Eray,Emin] Create Search Results Page for Web

### ISSUE THREAD

**Issue by ErayEroglu** [bounswe/bounswe2024group9#129]
* Create a search result page for website and connect it to the backend api
* Check mockups and diagrams before starting the implementation

* Deadline: 21.04.2024

**Comment by ErayEroglu** [comment]
I created a new branch for the implementation. We can use this branch until the implementation is done

**Comment by Mutti499** [comment]
Just before the exam night! I implemented search result basics and routes. Since the deadline is approaching, we need to make sure we stay on schedule. You can pull and revise it! Dont forget to add "_**concurrently**_" package to your systems to run both API database and web frontend. 

Commits:
[604b144](https://github.com/bounswe/bounswe2024group9/commit/604b144b2c9fc5b8f8d0d81efd8d14e5c0da9345)
[872edf6](https://github.com/bounswe/bounswe2024group9/commit/872edf627361491ffc20f0102c415fee2cc4772a)
[81e385c](https://github.com/bounswe/bounswe2024group9/commit/81e385cfd93d942a4357b80f0accd3f40b7fef0f)

**Comment by kristinatrajkovski** [comment]
I added some minor design changes as Eray asked me to rewiew [here](https://github.com/bounswe/bounswe2024group9/commit/a2507c19354f1fcbf32dc1f128f528286b78f10f).

Some things that I noticed but did not solve yet:
- when I try to search for the second time i.e. I am already at a detailed result page and I want to do another search, when I click on a button that I want to choose I see the URL change but nothing truly happens until I manually click on the URL and press enter. This is a problem. We should link and move on to another page immediately. 
- The nearby locations and locations from the same period should also be links. I think the whole point of us gathering that data is to link items together and give users opportunity to explore. However I truly struggled with that and need your help.

**Comment by Mutti499** [comment]
Nice feedback mate! I am on it

**Comment by ErayEroglu** [comment]
Thanks for the contribution @Mutti499, and I will work on the problems mentioned by @kristinatrajkovski ASAP.

**Comment by kristinatrajkovski** [comment]
I managed to fix the first bug I mentioned in my last review and other Null problems. On the last one.

**Comment by ErayEroglu** [comment]
Kristina solved the other problem also, eline sağlık. And then we sent a pull request to merge the branch with the main. There may be small updates regarding the design in future,  but for now we can say implementation is done. Thanks for not leaving me alone @kristinatrajkovski , @Mutti499. Your contribution was remarkable.
